# Generated by Django 2.0.13 on 2019-03-25 01:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190325_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='folling',
            field=models.ManyToManyField(related_name='_user_folling_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='followers',
            field=models.ManyToManyField(related_name='_user_followers_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
