# Generated by Django 2.0.13 on 2019-03-26 15:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_following'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='following',
        ),
        migrations.AddField(
            model_name='user',
            name='folling',
            field=models.ManyToManyField(related_name='_user_folling_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
